# Generated by Django 3.2.25 on 2024-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240406_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='occasion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
