# Generated by Django 3.2.25 on 2024-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_wishlist_occasion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
