# Generated by Django 3.2.25 on 2024-10-27 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20241016_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
