# Generated by Django 3.2.25 on 2024-10-27 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20241027_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
